### ISSUE TITLE
It is broken on steam deck.

### ISSUE THREAD

**Issue by RibhuNoodleBoodle** [zealottormunds/sh2cammod#5]
Adding the custom dlls through winecfg to enable the mod crashes the entire prefix. 

The dll in question is winmm.dll

I do get a warning to not touch this dll though so there is that.

**Comment by edude78** [comment]
Did you ever figure out how to fix it on Steamdeck?

**Comment by dowttie** [comment]
Got it working by renaming winmm.dll to dsound.dll and overriding that in winecfg instead.

**Comment by DXB6** [comment]
Just like magic.

**Comment by edude78** [comment]
Incredible this did the trick! Thanks so much.

**Comment by RibhuNoodleBoodle** [comment]
> Got it working by renaming winmm.dll to dsound.dll and overriding that in winecfg instead. No idea what side effects this may cause but it works well so far.

I'm shocked that the solution was that simple.

**Comment by RibhuNoodleBoodle** [comment]
Thank you very much guys! 

I am closing this thread

**Comment by DXB6** [comment]
> I renamed winmm to dsound, but when I override is that in the launch options? if so, mine looks like this:
> 
> WINEDLLOVERRIDES=“dinput8,d3d8=n,b,dsound” %command%
> 
> Is there something I’m doing wrong?

Move dsound in front of d3d8.
WINEDLLOVERRIDES=“dinput8,d3d8,dsound=n,b
